/**
 * tests/integration/task-decomposition/t3-spec-render-tasks-md.test.js
 *
 * Spec 226 / T-3: spec render による tasks/<id>.md 自動生成。
 *
 * REQ-10 / REQ-11 に対応。
 */

import { describe, it, before, after } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { renderTaskMarkdown, renderSpecMarkdown, runSpecRender } from "../../../src/spec/commands/render.js";
import { createTmpDir, removeTmpDir } from "../../support/builders/tmp-dir.js";
import { CanonicalFlowFixture, makeContainer } from "../../support/infrastructure/flow-setup.js";

// ── fixtures ────────────────────────────────────────────────────────────────

function sampleTask(overrides = {}) {
  return {
    id: "T-1",
    title: "Implement feature A",
    goal: "Deliver feature A end-to-end.",
    acceptance: ["All tests pass", "Docs updated"],
    implementation_notes: "Use existing helpers in lib/.",
    test_strategy: "Unit tests + integration gate.",
    parent: null,
    origin: "plan",
    added_round: 0,
    status: "pending",
    ...overrides,
  };
}

function minSpec(tasks) {
  return {
    goal: "g",
    scope: { in: [], out: [] },
    constraints: [],
    design_principles: [],
    overview: { modules: [], data_flow: [], decisions: [] },
    background: "bg",
    requirements: [],
    acceptance_criteria: [],
    clarifications: [],
    alternatives_considered: [],
    open_questions: [],
    ...(tasks !== undefined ? { tasks } : {}),
  };
}

const meta = { title: "test", featureBranch: "feature/test", created: "2026-04-24" };

// ── pure-function tests ─────────────────────────────────────────────────────

describe("T-3: spec render generates tasks/<id>.md", () => {
  it("generates tasks/<id>.md for each task in spec.json", () => {
    const tasks = [
      sampleTask({ id: "T-1", title: "First" }),
      sampleTask({ id: "T-2", title: "Second", parent: "T-1" }),
      sampleTask({ id: "T-3", title: "Third", parent: null }),
    ];
    for (const t of tasks) {
      const md = renderTaskMarkdown(t);
      // Each task renders as markdown with the task id and title in heading
      assert.match(md, new RegExp(`^# ${t.id}: ${t.title}`));
      // Verify the output is a non-empty string
      assert.ok(md.length > 0);
    }
  });

  it("markdown contains Goal / Acceptance / Implementation Notes / Test Strategy sections", () => {
    const task = sampleTask();
    const md = renderTaskMarkdown(task);

    assert.ok(md.includes("## Goal"), "missing Goal section");
    assert.ok(md.includes(task.goal), "goal text missing");

    assert.ok(md.includes("## Acceptance Criteria"), "missing Acceptance Criteria section");
    for (const a of task.acceptance) {
      assert.ok(md.includes(`- ${a}`), `missing acceptance criterion: ${a}`);
    }

    assert.ok(md.includes("## Implementation Notes"), "missing Implementation Notes section");
    assert.ok(md.includes(task.implementation_notes), "implementation_notes text missing");

    assert.ok(md.includes("## Test Strategy"), "missing Test Strategy section");
    assert.ok(md.includes(task.test_strategy), "test_strategy text missing");
  });

  it("markdown is deterministic (idempotent across re-renders)", () => {
    const task = sampleTask();
    const a = renderTaskMarkdown(task);
    const b = renderTaskMarkdown(task);
    assert.equal(a, b, "two renders of the same task must produce byte-identical output");
  });

  it("markdown contains manual-edit-forbidden marker", () => {
    const task = sampleTask();
    const md = renderTaskMarkdown(task);
    assert.ok(
      md.includes("<!-- Auto-generated by `sennel spec render` from spec.json.tasks[]. Do not edit manually. -->"),
      "manual-edit-forbidden HTML comment marker missing",
    );
  });

  it("spec.md Tasks section shows summary (title + goal) per task", () => {
    const tasks = [
      sampleTask({ id: "T-1", title: "Alpha feature", goal: "Ship alpha." }),
      sampleTask({ id: "T-2", title: "Beta feature", goal: "Ship beta.", added_round: 1 }),
    ];
    const spec = minSpec(tasks);
    const md = renderSpecMarkdown(spec, meta);

    assert.ok(md.includes("## Tasks"), "Tasks section heading missing in spec.md");

    // Each task line shows id, status, title
    assert.ok(md.includes("**T-1** [pending]: Alpha feature"), "T-1 summary line missing");
    assert.ok(md.includes("**T-2** [pending]: Beta feature"), "T-2 summary line missing");

    // Each task shows its goal indented beneath
    assert.ok(md.includes("  - Ship alpha."), "T-1 goal missing in spec.md Tasks section");
    assert.ok(md.includes("  - Ship beta."), "T-2 goal missing in spec.md Tasks section");

    // Each task shows a reference to tasks/<id>.md
    assert.ok(md.includes("see `tasks/T-1.md` for full spec"), "T-1 task file reference missing");
    assert.ok(md.includes("see `tasks/T-2.md` for full spec"), "T-2 task file reference missing");
  });

  describe("filesystem integration (runSpecRender)", () => {
    let tmp;
    before(() => { tmp = createTmpDir("t3-render-"); });
    after(() => { removeTmpDir(tmp); });

    it("render is additive-only (orphan md files are not deleted)", async () => {
      // Build the authoritative Spec and Task through the V1 Store.  The
      // renderer must resolve this active Flow's `001` location, never a
      // guessed root-level spec directory.
      const container = makeContainer(tmp);
      container.register("root", tmp);
      const fm = container.get("flowManager");
      const fixture = new CanonicalFlowFixture({
        flowManager: fm,
        specId: "001-test",
        runId: "run-001-test",
        request: "Render canonical Task markdown.",
        execution: { mode: "direct", baseBranch: "main", featureBranch: null },
        specRecord: minSpec(),
      }).create().addTask(sampleTask({ id: "T-1", title: "First task" })).registerActive();
      const specDir = fixture.location().directory;

      // Rendered Markdown is transient beneath .runtime, so an additive
      // orphan cannot pollute the cataloged Version authority.
      const tasksDir = path.join(specDir, ".runtime", "spec-render", "tasks");
      fs.mkdirSync(tasksDir, { recursive: true });
      fs.writeFileSync(path.join(tasksDir, "T-old.md"), "# orphan content\n");

      await runSpecRender([], container);

      // T-1.md should have been rendered
      assert.ok(
        fs.existsSync(path.join(tasksDir, "T-1.md")),
        "T-1.md was not created",
      );

      // Orphan T-old.md must still exist (additive-only, no deletion)
      assert.ok(
        fs.existsSync(path.join(tasksDir, "T-old.md")),
        "orphan T-old.md was deleted; render must be additive-only",
      );
      assert.equal(
        fs.readFileSync(path.join(tasksDir, "T-old.md"), "utf8"),
        "# orphan content\n",
        "orphan file content was modified",
      );
      assert.doesNotThrow(() => fm.loadReadOnly("001-test"), "rendered Markdown must stay outside the catalog authority");
      assert.equal(fs.existsSync(path.join(specDir, "spec.md")), false, "derived spec.md must not be retained in the Version root");
    });

    it("render creates tasks/ directory if not exists", async () => {
      // An explicit `--spec` is still supported, but must name a Version-1
      // Spec authority rather than a root-level legacy directory.
      const container2 = makeContainer(tmp);
      container2.register("root", tmp);
      const fm2 = container2.get("flowManager");
      const fixture = new CanonicalFlowFixture({
        flowManager: fm2,
        specId: "002-fresh",
        runId: "run-002-fresh",
        request: "Render a new canonical Task markdown document.",
        execution: { mode: "direct", baseBranch: "main", featureBranch: null },
        specRecord: minSpec(),
      }).create().addTask(sampleTask({ id: "T-A", title: "New task" }));
      const specDir = fixture.location().directory;
      const tasksDir = path.join(specDir, ".runtime", "spec-render", "tasks");
      // Confirm tasks/ does not exist yet
      assert.ok(!fs.existsSync(tasksDir), "tasks/ should not exist before render");

      await runSpecRender(["--spec", specDir], container2);

      // tasks/ directory should now exist
      assert.ok(
        fs.existsSync(tasksDir),
        "tasks/ directory was not created by render",
      );
      // And the task file should be inside it
      assert.ok(
        fs.existsSync(path.join(tasksDir, "T-A.md")),
        "T-A.md was not created inside tasks/",
      );
      assert.doesNotThrow(() => fm2.loadReadOnly("002-fresh"));
    });
  });
});
