#!/usr/bin/env node
/**
 * src/flow/commands/review.js
 *
 * sdd-forge flow review — code quality review after implementation.
 * Phases: confirm → draft (propose) → final (validate) → approve → apply
 *
 * --phase test: test sufficiency review before impl.
 * Internal pipeline: generate test design → compare with test code → auto-fix loop.
 */

import fs from "fs";
import path from "path";
import { parseArgs } from "../../lib/cli.js";
import { getSpecName } from "../../lib/flow-helpers.js";
import { loadSpecJson, resolveSpecDir } from "../../lib/spec-json.js";

async function loadReqMap(root, flow, kind) {
  try {
    const { loadFileMap, loadTestMap } = await import("../lib/req-map.js");
    const specDir = resolveSpecDir(path.resolve(root, flow.spec));
    return kind === "test" ? loadTestMap(specDir) : loadFileMap(specDir);
  } catch (err) {
    process.stderr.write(`  [review] ${kind}-map load skipped: ${err.message}\n`);
    return null;
  }
}
import { container, initContainer } from "../../lib/container.js";
import { Command } from "../../lib/command.js";

/**
 * Local helper for review-phase agent invocations. The Agent service handles
 * timeout and cwd internally; callers only provide the system prompt and
 * (optionally) commandId.
 */
const callReviewAgent = (agent, prompt, commandId, systemPrompt) =>
  agent.call(prompt, { commandId, systemPrompt });

function ensureAgent(commandId) {
  const agent = container.get("agent");
  if (!agent.resolve(commandId)) {
    throw new Error(`no AI agent configured for ${commandId} (set agent.default in config.json)`);
  }
  return agent;
}
import { runGit } from "../../lib/git-helpers.js";
import { EXIT_ERROR } from "../../lib/constants.js";
import { VALID_PHASES } from "../../lib/constants.js";
import { loadMergedGuardrails, filterByPhase } from "../../lib/guardrail.js";
import { resolveNodeFor, FLOW_DEFINITION } from "../definition.js";

const REVIEW_MAX_ATTEMPTS = resolveNodeFor(FLOW_DEFINITION, "review").maxAttempts;

/** Supported review phases and their descriptions. */
const REVIEW_PHASES = {
  test: "test sufficiency",
  spec: "spec completeness",
};

// Validate REVIEW_PHASES keys are a subset of VALID_PHASES
for (const key of Object.keys(REVIEW_PHASES)) {
  if (!VALID_PHASES.includes(key)) {
    throw new Error(`REVIEW_PHASES key '${key}' is not in VALID_PHASES`);
  }
}

/**
 * Resolve the merge-base SHA between HEAD and baseBranch. Throws with a
 * message that names `merge-base` and includes captured stderr when git
 * reports an error or returns an empty SHA.
 *
 * @param {string} root - repo root
 * @param {string} baseBranch - name/ref of the base branch
 * @returns {string} merge-base SHA (full)
 */
function resolveMergeBase(root, baseBranch) {
  const res = runGit(["-C", root, "merge-base", "HEAD", baseBranch]);
  if (!res.ok) {
    throw new Error(`git merge-base HEAD ${baseBranch} failed: ${res.stderr.trim()}`);
  }
  const sha = res.stdout.trim();
  if (!sha) {
    throw new Error(
      `git merge-base HEAD ${baseBranch} produced empty output (stderr: ${res.stderr.trim()})`,
    );
  }
  return sha;
}

/**
 * Resolve review target files from spec scope or git diff fallback.
 *
 * @param {string} root - repo root
 * @param {import("../../lib/flow-state.js").FlowState} flow - flow state
 * @param {string} mergeBase - merge-base SHA resolved by resolveMergeBase
 * @returns {string} diff text for review
 */
function resolveReviewTarget(root, flow, mergeBase) {
  // spec 207 / T8: read scope.in from spec.json via the single validated load
  // path. Throws when spec.json is missing or invalid — active flows must
  // have a valid spec.json by invariant.
  const specInput = path.resolve(root, flow.spec);
  const spec = loadSpecJson(specInput);
  const scopeFiles = Array.isArray(spec.scope?.in)
    ? spec.scope.in
        .map((l) => l.replace(/`/g, "").trim())
        .filter((l) => /\.(js|ts|json|md)$/.test(l))
    : [];

  if (scopeFiles.length > 0) {
    const diffs = [];
    for (const f of scopeFiles) {
      const abs = path.resolve(root, f);
      if (!fs.existsSync(abs)) continue;
      diffs.push(...collectCommittedAndStagedDiff(root, mergeBase, f));
    }
    if (diffs.length > 0) return diffs.join("\n");
  }

  // Fallback: committed diff against merge-base + staged changes
  return collectCommittedAndStagedDiff(root, mergeBase).join("\n");
}

/** Paths excluded from the fallback (whole-repo) diff in code review.
 *  These are auto-generated by sdd-forge pipelines and overwritten on build. */
const REVIEW_EXCLUDE_PATHS = ["docs/", "README.md", "AGENTS.md", ".sdd-forge/output/"];

/**
 * Build pathspec args for git diff.
 * When filePath is given, scopes to that single file.
 * Otherwise, includes all files except REVIEW_EXCLUDE_PATHS.
 * @param {string} [filePath]
 * @returns {string[]}
 */
function buildReviewPathspec(filePath) {
  if (filePath) return ["--", filePath];
  return ["--", ".", ...REVIEW_EXCLUDE_PATHS.map((p) => `:!${p}`)];
}

/**
 * Run git diff and return stdout, throwing on failure.
 * @param {string} root
 * @param {string[]} diffArgs - args between "diff" and pathspec
 * @param {string[]} pathspec - pathspec args from buildReviewPathspec
 * @param {string} label - human-readable label for error messages
 * @returns {string} trimmed stdout (may be empty)
 */
function runDiffOrThrow(root, diffArgs, pathspec, label) {
  const res = runGit(["-C", root, "diff", ...diffArgs, ...pathspec]);
  if (!res.ok) throw new Error(`${label} failed: ${res.stderr}`);
  return res.stdout.trim();
}

/**
 * Iterate the two review diff sources (committed vs baseRef, then staged)
 * and call `fn` for each. Keeps both `collectCommittedAndStagedDiff` and
 * `collectTouchedFiles` in sync when the set of sources changes.
 * @param {string} baseRef
 * @param {(source: { args: string[], label: string }) => void} fn
 */
function forEachReviewDiffSource(baseRef, fn) {
  fn({ args: [baseRef], label: `git diff ${baseRef}` });
  fn({ args: ["--cached"], label: "git diff --cached" });
}

/**
 * Collect non-empty committed (vs base) and staged diff outputs.
 * @param {string} root
 * @param {string} baseRef - diff starting point (merge-base SHA recommended)
 * @param {string} [filePath] - optional path to scope the diff to
 * @returns {string[]} array of non-empty diff outputs
 */
function collectCommittedAndStagedDiff(root, baseRef, filePath) {
  const pathspec = buildReviewPathspec(filePath);
  const out = [];
  forEachReviewDiffSource(baseRef, ({ args, label }) => {
    const text = runDiffOrThrow(root, args, pathspec, label);
    if (text) out.push(text);
  });
  return out;
}

/**
 * Build system prompt for the draft phase.
 * @param {Object[]} [guardrails=[]] - Pre-filtered guardrail articles (phase:review)
 */
function buildDraftSystemPrompt(guardrails = []) {
  const lines = [
    "You are a code quality reviewer. Analyze the following code changes and propose improvements.",
    "Focus on:",
    "- Duplicate code elimination",
    "- Naming improvements",
    "- Dead code removal",
    "- Design pattern consistency",
    "- Simplification opportunities",
    "",
    "Scope constraint (MANDATORY):",
    "- Propose changes ONLY for files that appear in the diff you are given (the touched files of this change set).",
    "- Do not propose changes to files outside the diff, even if you believe they could be improved.",
    "- Every proposal MUST include a '**File:** <path>' line pointing to a file present in the diff. Proposals without this line will be discarded.",
    "",
    "Output a numbered list of proposals in this format:",
    "### 1. <title>",
    "**File:** `<path>`",
    "**Issue:** <description of the problem>",
    "**Suggestion:** <concrete improvement>",
    "",
    "If no improvements are needed, output: NO_PROPOSALS",
  ];

  if (guardrails.length > 0) {
    lines.push("");
    lines.push("## Additional Guardrail Review Perspectives");
    lines.push("Also check the code against the following project-specific guardrail articles.");
    lines.push("If a violation is found, report it as a proposal using the same format above.");
    lines.push("");
    for (const g of guardrails) {
      lines.push(`- id: ${g.id}`);
      lines.push(`  title: ${g.title}`);
      lines.push(`  body: ${g.body.trim()}`);
    }
  }

  return lines.join("\n");
}

/**
 * Build system prompt for the final (validation) phase.
 */
function buildFinalSystemPrompt() {
  return [
    "You are a senior code reviewer validating refactoring proposals.",
    "For each proposal, judge whether it:",
    "1. Actually improves code quality",
    "2. Does not break existing behavior",
    "",
    "Output each proposal with a verdict:",
    "### <number>. <title>",
    "**Verdict:** APPROVED or REJECTED",
    "**Reason:** <brief justification>",
    "",
    "Be conservative. Reject proposals that are cosmetic-only or risk breaking behavior.",
  ].join("\n");
}

/**
 * Parse proposals from draft output.
 * Also extracts the first '**File:** <path>' marker in the body (if any).
 * @param {string} text
 * @returns {{ title: string, body: string, file: string|null }[]}
 */
function parseProposals(text) {
  const proposals = [];
  const parts = text.split(/^### /m).filter(Boolean);
  for (const part of parts) {
    const nlIdx = part.indexOf("\n");
    const title = nlIdx >= 0 ? part.slice(0, nlIdx).trim() : part.trim();
    const body = nlIdx >= 0 ? part.slice(nlIdx + 1).trim() : "";
    proposals.push({ title, body, file: extractProposalFile(body) });
  }
  return proposals;
}

/**
 * Extract the file path from a proposal body's '**File:**' marker.
 * Accepts `**File:** `path`` or `**File:** path` forms.
 * @param {string} body
 * @returns {string|null}
 */
function extractProposalFile(body) {
  if (!body) return null;
  const m = body.match(/\*\*File:\*\*\s*`?([^`\n]+?)`?\s*$/m);
  if (!m) return null;
  const file = m[1].trim();
  return file || null;
}

/**
 * Collect the set of files touched by the current change set.
 * The "touched" set is the union of:
 *   - files changed in the committed diff against baseRef (`git diff <baseRef>`)
 *   - files changed in the staged (index) diff (`git diff --cached`)
 * Untracked files that are not staged are intentionally NOT included — this
 * matches the review pipeline's scope, which only considers changes that are
 * either committed on the feature branch or staged for commit.
 * @param {string} root
 * @param {string} baseRef - diff starting point (merge-base SHA recommended)
 * @returns {Set<string>}
 */
function collectTouchedFiles(root, baseRef) {
  const touched = new Set();
  forEachReviewDiffSource(baseRef, ({ args, label }) => {
    const res = runGit(["-C", root, "diff", "--name-only", ...args]);
    if (!res.ok) throw new Error(`git diff --name-only (${label}) failed: ${res.stderr}`);
    for (const line of res.stdout.split("\n")) {
      const p = line.trim();
      if (p) touched.add(p);
    }
  });
  return touched;
}

/**
 * Filter proposals to keep only those whose 'file' is in the touched set.
 * Proposals without an extractable file are dropped as well.
 * @param {{title: string, body: string, file: string|null}[]} proposals
 * @param {Set<string>} touchedFiles
 * @returns {{kept: object[], excluded: {outOfScope: number, missingFile: number}}}
 */
function filterProposalsByScope(proposals, touchedFiles) {
  const kept = [];
  const excluded = { outOfScope: 0, missingFile: 0 };
  for (const p of proposals) {
    if (!p.file) {
      excluded.missingFile += 1;
      continue;
    }
    if (!touchedFiles.has(p.file)) {
      excluded.outOfScope += 1;
      continue;
    }
    kept.push(p);
  }
  return { kept, excluded };
}

/**
 * Parse verdicts from final output and merge into proposals.
 * @param {string} text
 * @param {{ title: string, body: string }[]} proposals
 * @returns {{ title: string, body: string, verdict: string, reason: string }[]}
 */
function mergeVerdicts(text, proposals) {
  const verdictMap = new Map();
  const parts = text.split(/^### /m).filter(Boolean);
  for (const part of parts) {
    const numMatch = part.match(/^(\d+)\./);
    if (!numMatch) continue;
    const idx = parseInt(numMatch[1], 10) - 1;
    const verdictMatch = part.match(/\*\*Verdict:\*\*\s*(APPROVED|REJECTED)/i);
    const reasonMatch = part.match(/\*\*Reason:\*\*\s*(.+)/);
    verdictMap.set(idx, {
      verdict: verdictMatch ? verdictMatch[1].toUpperCase() : "REJECTED",
      reason: reasonMatch ? reasonMatch[1].trim() : "",
    });
  }

  return proposals.map((p, i) => {
    const v = verdictMap.get(i) || { verdict: "REJECTED", reason: "No verdict provided" };
    return { ...p, verdict: v.verdict, reason: v.reason };
  });
}

/**
 * Write review.md for the current spec under specDir, using formatReviewMd
 * as the single source of truth for the on-disk format. Returns the absolute
 * path written.
 * @param {string} root
 * @param {object} flow
 * @param {object[]} results
 * @returns {string} absolute path of review.md
 */
function writeReviewMd(root, flow, results) {
  const specDir = path.dirname(path.resolve(root, flow.spec));
  const reviewPath = path.join(specDir, "review.md");
  fs.writeFileSync(reviewPath, formatReviewMd(results));
  return reviewPath;
}

const NO_PROPOSALS_MARKER = "_No proposals generated for this spec._";

/**
 * Generate review.md content.
 */
function formatReviewMd(results) {
  const lines = ["# Code Review Results", ""];
  if (results.length === 0) {
    lines.push(NO_PROPOSALS_MARKER);
    lines.push("");
    return lines.join("\n");
  }
  for (const r of results) {
    const mark = r.verdict === "APPROVED" ? "[x]" : "[ ]";
    lines.push(`### ${mark} ${r.title}`);
    lines.push(r.body);
    lines.push("");
    lines.push(`**Verdict:** ${r.verdict}`);
    if (r.reason) lines.push(`**Reason:** ${r.reason}`);
    lines.push("");
  }
  return lines.join("\n");
}

/**
 * Build the final validation prompt from the scope-filtered proposal set.
 * The AI is asked to emit verdicts numbered 1..N matching the array order so
 * `mergeVerdicts` can map verdict[i] back to proposals[i] without drift.
 */
function buildFinalValidationPrompt(proposals, diff) {
  const numbered = proposals
    .map((p, i) => `### ${i + 1}. ${p.title}\n${p.body}`)
    .join("\n\n");
  return [
    "Validate these refactoring proposals:",
    "",
    numbered,
    "",
    "## Original diff for context:",
    diff,
  ].join("\n");
}

/**
 * Build the apply prompt from approved proposals and diff.
 */
function buildApplyPrompt(approved, diff) {
  const proposalText = approved
    .map((p, i) => `### ${i + 1}. ${p.title}\n${p.body}`)
    .join("\n\n");

  return [
    "Apply the following approved refactoring proposals to the code.",
    "Make only the changes described. Do not add unrelated improvements.",
    "",
    "## Approved Proposals",
    proposalText,
    "",
    "## Current Diff (for context)",
    diff,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Common review loop
// ---------------------------------------------------------------------------

/**
 * Run a review-fix loop up to maxRetries times.
 * @param {Object} opts
 * @param {number} opts.maxRetries - Maximum iterations
 * @param {string} opts.label - Log label (e.g. "test-review", "spec-review")
 * @param {boolean} opts.dryRun - Skip fix phase if true
 * @param {() => Promise<{issues: Object[], raw: string}>} opts.detect - Detect issues. Return { issues, raw }.
 * @param {(raw: string) => Promise<void>} opts.fix - Apply fixes based on raw detection output.
 * @returns {Promise<{history: string[], finalIssues: Object[], verdict: string}>}
 */
async function runReviewLoop({ maxRetries, label, dryRun, detect, fix }) {
  const history = [];
  let finalIssues = [];

  for (let attempt = 0; attempt < maxRetries; attempt++) {
    console.error(`  [${label}] Analysis (attempt ${attempt + 1}/${maxRetries})...`);
    const { issues, raw } = await detect();
    history.push(raw);

    if (issues.length === 0) {
      console.error(`  [${label}] No issues found. PASS.`);
      finalIssues = [];
      break;
    }

    console.error(`  [${label}] ${issues.length} issue(s) found.`);
    finalIssues = issues;

    if (dryRun) {
      console.error(`  [${label}] (dry-run: skipping auto-fix)`);
      break;
    }

    console.error(`  [${label}] Applying fixes...`);
    await fix(raw);
  }

  // Verification detect: if loop ended with issues, run one more detect to check
  // whether the last fix resolved them. This handles the case where the previous
  // code skipped fix on the last iteration, missing fixes that resolved all issues.
  if (finalIssues.length > 0 && !dryRun) {
    console.error(`  [${label}] Verification detect...`);
    const { issues, raw } = await detect();
    history.push(raw);
    if (issues.length === 0) {
      console.error(`  [${label}] Verification PASS — all issues resolved.`);
      finalIssues = [];
    } else {
      console.error(`  [${label}] Verification: ${issues.length} issue(s) still remain.`);
      finalIssues = issues;
    }
  }

  const verdict = finalIssues.length === 0 ? "PASS" : "FAIL";
  return { history, finalIssues, verdict };
}

// ---------------------------------------------------------------------------
// Test review pipeline (--phase test)
// ---------------------------------------------------------------------------

/**
 * Render spec.json.requirements as plain-text bullets for AI prompts. Post-T8
 * there is no regex-based spec.md Requirements extraction.
 */
function extractRequirements(spec) {
  const items = Array.isArray(spec?.requirements) ? spec.requirements : [];
  if (items.length === 0) return "";
  return items
    .map((r) => `- ${r.id}${r.priority ? ` [${r.priority}]` : ""}: ${r.desc}`)
    .join("\n");
}

/**
 * Collect test files from spec-local tests/ and project tests/.
 * Spec-local takes precedence for same-name files.
 * @param {string} root
 * @param {string} specDir - relative spec directory
 * @returns {{ name: string, content: string, source: string }[]}
 */
function collectTestFiles(root, specDir) {
  const files = new Map();

  // Project-level tests/ (fallback)
  const projectTestDir = path.resolve(root, "tests");
  if (fs.existsSync(projectTestDir)) {
    collectTestsRecursive(projectTestDir, projectTestDir, files, "tests/");
  }

  // Spec-local tests/ (takes precedence)
  const specTestDir = path.resolve(root, specDir, "tests");
  if (fs.existsSync(specTestDir)) {
    collectTestsRecursive(specTestDir, specTestDir, files, `${specDir}/tests/`);
  }

  return Array.from(files.values());
}

/**
 * Recursively collect test files from a directory.
 */
function collectTestsRecursive(dir, baseDir, fileMap, sourcePrefix) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      collectTestsRecursive(full, baseDir, fileMap, sourcePrefix);
    } else if (/\.(test|spec)\.(js|ts|mjs)$/.test(entry.name)) {
      const relName = path.relative(baseDir, full);
      const content = fs.readFileSync(full, "utf8");
      fileMap.set(relName, { name: relName, content, source: sourcePrefix + relName });
    }
  }
}

/**
 * Build the test design generation prompt.
 */
function buildTestDesignPrompt(requirements) {
  return [
    "You are a test design expert. Based on the following spec requirements, generate a comprehensive test design.",
    "List what should be tested, including:",
    "- Happy path scenarios",
    "- Edge cases and boundary conditions",
    "- Error paths and failure modes",
    "- Test type balance (unit / integration / acceptance)",
    "",
    "Output format:",
    "### Test Design",
    "For each test case:",
    "- **TC-N: <title>**",
    "  - Type: unit|integration|acceptance",
    "  - Input: <description>",
    "  - Expected: <description>",
    "",
    "## Requirements",
    requirements,
  ].join("\n");
}

/**
 * Serialize test files into markdown code blocks for prompts.
 */
function formatTestFilesForPrompt(testFiles) {
  if (testFiles.length === 0) return "(no test files found)";
  return testFiles
    .map((f) => `### ${f.source}\n\`\`\`\n${f.content}\n\`\`\``)
    .join("\n\n");
}

/**
 * Build the gap analysis prompt.
 */
function buildGapAnalysisPrompt(testDesign, testFiles) {
  return [
    "You are a test quality reviewer. Compare the test design against actual test code and identify gaps.",
    "",
    "For each gap, output:",
    "### GAP-N: <title>",
    "**Missing:** <what is not tested>",
    "**Severity:** HIGH|MEDIUM|LOW",
    "**Fix:** <concrete suggestion for test code>",
    "",
    "If all test cases are adequately covered, output: NO_GAPS",
    "",
    "## Test Design",
    testDesign,
    "",
    "## Existing Test Code",
    formatTestFilesForPrompt(testFiles),
  ].join("\n");
}

/**
 * Build the test fix prompt.
 */
function buildTestFixPrompt(gaps, testFiles) {
  return [
    "You are a test engineer. Fix the following gaps in the test code.",
    "Output the complete updated test file(s) with fixes applied.",
    "For each file, output:",
    "### FILE: <path>",
    "```",
    "<complete file content>",
    "```",
    "",
    "Only modify files that need changes. Do not add unrelated tests.",
    "Note: constant definitions may be wrapped in Object.freeze(), Object.seal(), or similar. When writing regex patterns to match definitions, account for these wrappers (e.g. `=\\s*(?:Object\\.freeze\\()?\\[` instead of `=\\s*\\[`).",
    "",
    "## Gaps to fix",
    gaps,
    "",
    "## Current test code",
    formatTestFilesForPrompt(testFiles),
  ].join("\n");
}

/**
 * Parse gap analysis output.
 * @param {string} text
 * @returns {{ title: string, body: string }[]}
 */
function parseGaps(text) {
  if (/NO_GAPS/i.test(text)) return [];
  const gaps = [];
  const parts = text.split(/^### GAP-/m).filter(Boolean);
  for (const part of parts) {
    const nlIdx = part.indexOf("\n");
    const title = nlIdx >= 0 ? part.slice(0, nlIdx).trim() : part.trim();
    const body = nlIdx >= 0 ? part.slice(nlIdx + 1).trim() : "";
    gaps.push({ title, body });
  }
  return gaps;
}

/**
 * Parse file fix output and apply to disk.
 * @param {string} text - AI output with ### FILE: <path> blocks
 * @param {string} root
 * @returns {string[]} paths of files written
 */
function applyTestFixes(text, root) {
  const written = [];
  const fileParts = text.split(/^### FILE:\s*/m).filter(Boolean);
  for (const part of fileParts) {
    const nlIdx = part.indexOf("\n");
    if (nlIdx < 0) continue;
    const filePath = part.slice(0, nlIdx).trim();
    const codeMatch = part.match(/```(?:\w*)\n([\s\S]*?)```/);
    if (!codeMatch) continue;
    const absPath = path.resolve(root, filePath);
    const dir = path.dirname(absPath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(absPath, codeMatch[1]);
    written.push(filePath);
  }
  return written;
}

/**
 * Format test-review.md content.
 */
function formatTestReviewMd(testDesign, gapHistory, finalVerdict, remainingGaps) {
  const lines = ["# Test Review Results", ""];
  lines.push("## Test Design");
  lines.push("See [tests/spec.md](tests/spec.md) for the full test design.");
  lines.push("");
  lines.push("## Gap Analysis");
  for (let i = 0; i < gapHistory.length; i++) {
    if (gapHistory.length > 1) lines.push(`### Iteration ${i + 1}`);
    lines.push(gapHistory[i]);
    lines.push("");
  }
  lines.push(`## Verdict: ${finalVerdict}`);
  if (finalVerdict === "FAIL" && remainingGaps.length > 0) {
    lines.push("");
    lines.push("### Remaining Gaps");
    for (const g of remainingGaps) {
      lines.push(`- ${g.title}`);
      lines.push(`  ${g.body}`);
    }
  }
  return lines.join("\n");
}

/**
 * Run the test review pipeline.
 */
async function runTestReview(root, flow, config, dryRun) {
  const specDir = path.dirname(flow.spec);
  const specInput = path.resolve(root, flow.spec);

  // spec 207 / T8: require spec.json for the test review pipeline. No fallback
  // to spec.md; loadSpecJson throws when spec.json is missing or invalid.
  const spec = loadSpecJson(specInput);
  const requirements = extractRequirements(spec);
  if (!requirements) {
    console.error("Error: no requirements defined in spec.json");
    process.exit(EXIT_ERROR);
  }

  // spec 241 R8: check test-map.json for untested requirements
  const testMap = await loadReqMap(root, flow, "test");
  if (testMap && Object.keys(testMap).length > 0) {
    const untested = requirements.filter((r) => {
      const tests = testMap[r.id] || [];
      return tests.length === 0;
    });
    if (untested.length > 0) {
      console.error(`  [test-review] test-map.json: ${untested.length} requirement(s) have no tests:`);
      for (const r of untested) {
        console.error(`    - ${r.id}: ${r.desc}`);
      }
    }
  }

  const agent = ensureAgent("flow.test.review");

  // Step 1: Generate test design
  console.error("  [test-review] Generating test design...");
  const testDesignPrompt = buildTestDesignPrompt(requirements);
  const testDesign = await callReviewAgent(
    agent, testDesignPrompt, "flow.test.review",
    "You are a test design expert. Output a structured test design.",
  );
  // Save test design as tests/spec.md
  const testsDir = path.resolve(root, specDir, "tests");
  if (!fs.existsSync(testsDir)) fs.mkdirSync(testsDir, { recursive: true });
  const testSpecPath = path.join(testsDir, "spec.md");
  fs.writeFileSync(testSpecPath, `# Test Design\n\n${testDesign}\n`);
  console.error(`  [test-review] Test design saved to ${path.relative(root, testSpecPath)}`);

  // Step 2-3: Compare and retry loop (using common runReviewLoop)
  let testFiles = collectTestFiles(root, specDir);

  const { history: gapHistory, finalIssues: finalGaps, verdict } = await runReviewLoop({
    maxRetries: REVIEW_MAX_ATTEMPTS,
    label: "test-review",
    dryRun,
    async detect() {
      const detectPrompt = buildGapAnalysisPrompt(testDesign, testFiles);
      const raw = await callReviewAgent(
        agent, detectPrompt, "flow.test.review",
        "You are a test quality reviewer. Identify gaps between test design and test code.",
      );
      return { issues: parseGaps(raw), raw };
    },
    async fix(raw) {
      const fixPrompt = buildTestFixPrompt(raw, testFiles);
      const fixResult = await callReviewAgent(
        agent, fixPrompt, "flow.test.review",
        "You are a test engineer. Fix test gaps by writing complete updated test files.",
      );
      const written = applyTestFixes(fixResult, root);
      if (written.length > 0) {
        console.error(`  [test-review] Fixed ${written.length} file(s): ${written.join(", ")}`);
      } else {
        console.error("  [test-review] No files were updated by fix attempt.");
      }
      testFiles = collectTestFiles(root, specDir);
    },
  });
  const testReviewPath = path.join(path.resolve(root, specDir), "test-review.md");
  fs.writeFileSync(testReviewPath, formatTestReviewMd(testDesign, gapHistory, verdict, finalGaps));
  console.error(`  [test-review] Results saved to ${path.relative(root, testReviewPath)}`);

  if (verdict === "PASS") {
    console.log("Test review PASS. All test cases are adequately covered.");
  } else {
    console.log(`Test review FAIL. ${finalGaps.length} gap(s) remaining after ${REVIEW_MAX_ATTEMPTS} attempts.`);
    console.error(`  [test-review] verdict=FAIL gaps=${finalGaps.length}`);
    process.exit(EXIT_ERROR);
  }
}

// ---------------------------------------------------------------------------
// Spec review pipeline (--phase spec)
// ---------------------------------------------------------------------------

/**
 * Build a context-search query from a spec.json object. Post-T8 this replaces
 * the regex-based Goal / Scope extraction from spec.md.
 */
function extractGoalAndScope(spec) {
  const parts = [];
  if (spec?.goal) parts.push(spec.goal);
  if (Array.isArray(spec?.scope?.in) && spec.scope.in.length) {
    parts.push(spec.scope.in.join("\n"));
  }
  return parts.join("\n");
}

/**
 * Build the spec review prompt.
 * @param {string} specText - Full spec.md content
 * @param {Object[]} contextEntries - Related codebase entries from contextSearch
 * @returns {string}
 */
function buildSpecReviewPrompt(specText, contextEntries) {
  const contextText = contextEntries.map((e) =>
    `- **${e.file}**: ${e.summary || "(no summary)"}${e.detail ? "\n  " + e.detail : ""}`
  ).join("\n");

  return [
    "You are a spec completeness reviewer. Analyze the following spec against the codebase context to identify oversights.",
    "Focus on:",
    "- Files or features around modules in Scope that the spec does not mention",
    "- Related code not explicitly listed in Out of Scope",
    "- External references (skill templates, tests, config) that depend on files to be deleted or moved",
    "- Contradictions or gaps between requirements",
    "",
    "Output a numbered list of proposals in this format:",
    "### 1. <title>",
    "**File:** `<path>` (the file that the spec overlooks)",
    "**Issue:** <what the spec misses or gets wrong>",
    "**Suggestion:** <concrete improvement to the spec>",
    "",
    "If no oversights are found, output: NO_PROPOSALS",
    "",
    "## Spec",
    specText,
    "",
    "## Codebase Context (related files)",
    contextText,
  ].join("\n");
}

/**
 * Build the spec fix prompt.
 * @param {string} specText - Current spec.md content
 * @param {string} proposals - Approved proposals text
 * @returns {string}
 */
function buildSpecFixPrompt(specText, proposals) {
  return [
    "Apply the following approved proposals to improve the spec.",
    "Output ONLY the complete updated spec.md content. Do not include any preamble, explanation, or commentary before or after the spec content.",
    "Do not wrap the output in markdown fences.",
    "The output must start with the spec's first heading (e.g. '# Feature Specification').",
    "Make only the changes described in the proposals. Do not add unrelated modifications.",
    "Preserve all existing sections and formatting.",
    "",
    "## Approved Proposals",
    proposals,
    "",
    "## Current Spec",
    specText,
  ].join("\n");
}

/**
 * Format spec-review.md content.
 * @param {string[]} history - Raw review outputs per iteration
 * @param {string} verdict - PASS or FAIL
 * @param {Object[]} finalIssues - Remaining issues if FAIL
 * @returns {string}
 */
function formatSpecReviewMd(history, verdict, finalIssues) {
  const lines = ["# Spec Review Results", ""];
  lines.push("## Review Iterations");
  for (let i = 0; i < history.length; i++) {
    if (history.length > 1) lines.push(`### Iteration ${i + 1}`);
    lines.push(history[i]);
    lines.push("");
  }
  lines.push(`## Verdict: ${verdict}`);
  if (verdict === "FAIL" && finalIssues.length > 0) {
    lines.push("");
    lines.push("### Remaining Issues");
    for (const p of finalIssues) {
      lines.push(`- ${p.title}`);
      if (p.body) lines.push(`  ${p.body}`);
    }
  }
  return lines.join("\n");
}

/**
 * Run the spec review pipeline.
 */
async function runSpecReview(root, flow, config, dryRun) {
  const specInput = path.resolve(root, flow.spec);
  const specDir = path.dirname(flow.spec);
  // Post-T8: the AI spec-review pipeline still operates on rendered spec.md
  // text (since the AI's natural output format is Markdown), but the md file
  // is an authoritative render of spec.json — never parsed for structured data
  // outside of this function. Throws if spec.json is missing or invalid.
  const spec = loadSpecJson(specInput);
  const specPath = path.join(path.dirname(specInput), "spec.md");
  if (!fs.existsSync(specPath)) {
    console.error("Error: spec.md not found (run 'sdd-forge spec render' first)");
    process.exit(EXIT_ERROR);
  }

  // Load analysis data once (entries don't change during review)
  let analysisData = null;
  try {
    const { loadAnalysisEntries, contextSearch: ctxSearch } = await import("../lib/get-context.js");
    analysisData = { ...loadAnalysisEntries(root), ctxSearch };
  } catch (e) {
    console.error(`  [spec-review] Warning: failed to load codebase context: ${e.message}`);
  }

  const agent = ensureAgent("flow.spec.review");
  ensureAgent("flow.impl.review.final");

  const { history, finalIssues, verdict } = await runReviewLoop({
    maxRetries: REVIEW_MAX_ATTEMPTS,
    label: "spec-review",
    dryRun,
    async detect() {
      // Re-read spec and recompute context on each iteration (spec may have been modified by fix)
      const specText = fs.readFileSync(specPath, "utf8");
      let contextEntries = [];
      if (analysisData) {
        const searchQuery = extractGoalAndScope(spec);
        if (searchQuery) {
          contextEntries = await analysisData.ctxSearch(analysisData.entries, analysisData.analysis, searchQuery, root);
        }
      }
      const detectPrompt = buildSpecReviewPrompt(specText, contextEntries);
      const raw = await callReviewAgent(
        agent, detectPrompt, "flow.spec.review",
        "You are a spec completeness reviewer. Identify oversights in the spec.",
      );
      if (raw.includes("NO_PROPOSALS")) return { issues: [], raw };
      const issues = parseProposals(raw);
      return { issues, raw };
    },
    async fix(raw) {
      const specText = fs.readFileSync(specPath, "utf8");
      const proposals = parseProposals(raw);
      const validationPrompt = [
        "Validate these spec improvement proposals:",
        "",
        raw,
        "",
        "## Current spec for context:",
        specText,
      ].join("\n");
      const validationResult = await callReviewAgent(
        agent, validationPrompt, "flow.impl.review.final", buildFinalSystemPrompt(),
      );
      const results = mergeVerdicts(validationResult, proposals);
      const approved = results.filter((r) => r.verdict === "APPROVED");

      if (approved.length === 0) {
        console.error("  [spec-review] All proposals rejected. Skipping fix.");
        return;
      }

      console.error(`  [spec-review] ${approved.length} proposal(s) approved. Applying to spec...`);

      const approvedText = approved.map((p, i) => `### ${i + 1}. ${p.title}\n${p.body}`).join("\n\n");
      const specFixPrompt = buildSpecFixPrompt(specText, approvedText);
      const fixResult = await callReviewAgent(
        agent, specFixPrompt, "flow.spec.review",
        "You are a spec writer. Apply the approved proposals to produce an updated spec.",
      );

      // Strip preamble and markdown fences from AI output
      const cleaned = stripPreamble(fixResult);
      if (!isValidSpecOutput(cleaned)) {
        console.error("  [spec-review] WARNING: AI output is not valid spec content. Keeping original spec.md.");
        return;
      }
      fs.writeFileSync(specPath, cleaned + "\n");
      console.error("  [spec-review] spec.md updated.");
    },
  });

  // Save review results
  const reviewPath = path.join(path.resolve(root, specDir), "spec-review.md");
  fs.writeFileSync(reviewPath, formatSpecReviewMd(history, verdict, finalIssues));
  console.error(`  [spec-review] Results saved to ${path.relative(root, reviewPath)}`);
  console.error(`  [spec-review] verdict=${verdict} issues=${finalIssues.length}`);

  if (verdict === "PASS") {
    console.log("Spec review PASS. No oversights found.");
  } else {
    console.log(`Spec review FAIL. ${finalIssues.length} issue(s) remaining after ${REVIEW_MAX_ATTEMPTS} attempts.`);
    process.exit(EXIT_ERROR);
  }
}

async function runReview(rawArgs) {
  const root = container.get("root");
  const cli = parseArgs(rawArgs, {
    flags: ["--dry-run", "--skip-confirm"],
    options: ["--phase"],
    defaults: { dryRun: false, skipConfirm: false, phase: null },
  });

  if (cli.help) {
    const phaseDesc = Object.entries(REVIEW_PHASES).map(([k, v]) => `'${k}' for ${v}`).join(", ");
    console.log([
      "Usage: sdd-forge flow review [options]",
      "",
      "Options:",
      `  --phase <type>   Review phase: ${phaseDesc}`,
      "  --dry-run        Show proposals without applying",
      "  --skip-confirm   Skip initial confirmation prompt",
    ].join("\n"));
    return;
  }

  if (cli.phase && !REVIEW_PHASES[cli.phase]) {
    const supported = Object.keys(REVIEW_PHASES).join(", ");
    console.error(`Error: unknown phase '${cli.phase}'. Supported: ${supported}`);
    process.exit(EXIT_ERROR);
  }

  const flow = container.get("flowManager").load();
  if (!flow) {
    console.error("Error: no active flow (flow.json not found)");
    process.exit(EXIT_ERROR);
  }

  const config = container.get("config");
  if (!config || Object.keys(config).length === 0) {
    console.error("Error: failed to load config.json");
    process.exit(EXIT_ERROR);
  }

  // Test review pipeline
  if (cli.phase === "test") {
    await runTestReview(root, flow, config, cli.dryRun);
    return;
  }

  // Spec review pipeline
  if (cli.phase === "spec") {
    await runSpecReview(root, flow, config, cli.dryRun);
    return;
  }

  // Resolve merge-base once and use it as the single diff starting point.
  // Failure here intentionally propagates — there is no silent fallback to
  // baseBranch tip (spec 223).
  const mergeBase = resolveMergeBase(root, flow.baseBranch);

  // Resolve target diff
  const diff = resolveReviewTarget(root, flow, mergeBase);
  if (!diff) {
    console.log("No changes detected. Skipping review.");
    return;
  }

  // spec 241 R7: enrich diff with file-map context for scoped review
  let reviewInput = diff;
  const fileMap = await loadReqMap(root, flow, "file");
  if (fileMap && Object.keys(fileMap).length > 0) {
    const mapLines = Object.entries(fileMap).map(([reqId, files]) =>
      `- ${reqId}: ${files.join(", ")}`,
    );
    reviewInput = `## Requirement-File Mapping\n${mapLines.join("\n")}\n\n## Diff\n${diff}`;
  }

  // --- Draft phase ---
  console.error("  [draft] Generating proposals...");
  const reviewGuardrails = filterByPhase(loadMergedGuardrails(root), "review");
  const draftAgent = ensureAgent("flow.impl.review.draft");
  const draftResult = await callReviewAgent(draftAgent, reviewInput, "flow.impl.review.draft", buildDraftSystemPrompt(reviewGuardrails));

  if (draftResult.includes("NO_PROPOSALS")) {
    console.log("No improvement proposals found. Code looks good.");
    writeReviewMd(root, flow, []);
    return;
  }

  const rawProposals = parseProposals(draftResult);
  if (rawProposals.length === 0) {
    console.log("No structured proposals found.");
    writeReviewMd(root, flow, []);
    return;
  }

  const touchedFiles = collectTouchedFiles(root, mergeBase);
  const { kept: proposals, excluded } = filterProposalsByScope(rawProposals, touchedFiles);
  if (excluded.outOfScope > 0 || excluded.missingFile > 0) {
    console.error(
      `  [draft] excluded ${excluded.outOfScope} out-of-scope + ${excluded.missingFile} missing-file proposal(s).`,
    );
  }
  if (proposals.length === 0) {
    console.log("All proposals were outside the current change scope. No review output.");
    writeReviewMd(root, flow, []);
    return;
  }

  console.error(`  [draft] ${proposals.length} proposal(s) generated (after scope filter).`);

  // --- Final phase ---
  console.error("  [final] Validating proposals...");
  const finalAgent = ensureAgent("flow.impl.review.final");
  const finalPrompt = buildFinalValidationPrompt(proposals, diff);

  const finalResult = await callReviewAgent(finalAgent, finalPrompt, "flow.impl.review.final", buildFinalSystemPrompt());

  const results = mergeVerdicts(finalResult, proposals);
  const approved = results.filter((r) => r.verdict === "APPROVED");
  const rejected = results.filter((r) => r.verdict === "REJECTED");

  // Write review.md
  const reviewPath = writeReviewMd(root, flow, results);
  console.error(`  [final] Results saved to ${path.relative(root, reviewPath)}`);
  console.error(`  [final] ${approved.length} approved, ${rejected.length} rejected.`);

  if (approved.length === 0) {
    console.log("All proposals were rejected. No changes to apply.");
    return;
  }

  // --- Display and approval ---
  console.log("");
  console.log("Approved proposals:");
  for (const p of approved) {
    console.log(`  - ${p.title}`);
  }
  console.log("");

  if (cli.dryRun) {
    console.log("(dry-run: skipping apply phase)");
    return;
  }

  console.log("Review the proposals above and in review.md.");
}

/**
 * Strip AI preamble text that appears before the actual spec content.
 * Also removes markdown fences wrapping the spec.
 * @param {string} text
 * @returns {string}
 */
function stripPreamble(text) {
  if (!text) return text;

  // Strip markdown fences first
  let cleaned = text.replace(/^```(?:markdown)?\s*\n?/i, "").replace(/\n?```\s*$/i, "").trim();

  // Find the first spec header
  const headerMatch = cleaned.match(/^(#\s+Feature Specification|##\s+Goal)/m);
  if (!headerMatch) return cleaned;

  // Remove everything before the header
  const headerIdx = cleaned.indexOf(headerMatch[0]);
  if (headerIdx > 0) {
    cleaned = cleaned.slice(headerIdx);
  }

  return cleaned;
}

/**
 * Validate that AI output looks like spec content, not garbage text.
 * @param {string} text
 * @returns {boolean}
 */
function isValidSpecOutput(text) {
  if (!text || !text.trim()) return false;
  return /^#\s+Feature Specification/m.test(text) || /^##\s+Goal/m.test(text);
}

export {
  parseProposals, mergeVerdicts, formatReviewMd, resolveReviewTarget,
  resolveMergeBase,
  buildDraftSystemPrompt, buildFinalSystemPrompt, buildFinalValidationPrompt,
  NO_PROPOSALS_MARKER,
  collectTouchedFiles, filterProposalsByScope, extractProposalFile,
  REVIEW_MAX_ATTEMPTS, REVIEW_PHASES, extractRequirements, collectTestFiles, parseGaps,
  applyTestFixes, formatTestReviewMd, runReviewLoop,
  extractGoalAndScope, buildSpecReviewPrompt, formatSpecReviewMd,
  isValidSpecOutput, stripPreamble, buildTestFixPrompt,
};

export default class FlowReviewCommand extends Command {
  static outputMode = "raw";
  async execute(ctx) {
    return runReview(ctx._rawArgs || []);
  }
}

// Direct-invocation entrypoint: `node src/flow/commands/review.js ...args`.
// Used by RunReviewCommand (src/flow/lib/run-review.js) as a subprocess so
// AI review can run with its own timeout.
if (import.meta.url === `file://${process.argv[1]}`) {
  initContainer();
  runReview(process.argv.slice(2)).catch((err) => {
    console.error(err?.stack || String(err));
    process.exit(1);
  });
}
